### ISSUE TITLE
Human-friendly revert reasons and hints

### ISSUE THREAD

**Issue by ongrid** [lidofinance/lido-oracle#64]
All known revert reasons should be decorated by either INFO or WARNING info messages instead of tracebacks.

```
INFO: EPOCH_IS_TOO_OLD
INFO: EPOCH_HAS_NOT_YET_BEGUN
WARNING: MEMBER_NOT_FOUND
INFO: ALREADY_SUBMITTED
WARNING: REPORTED_MORE_DEPOSITED
WARNING: REPORTED_LESS_VALIDATORS
```

The messages should be clear and descriptive.

**Comment by ongrid** [comment]
in `daemon_v2` `ALREADY_SUBMITTED` now looks like this

```
   ERROR 2020-12-11 14:13:17 <daemon> Unexpected exception. <class 'web3.exceptions.SolidityError'>
Traceback (most recent call last):
  File "/Users/kirill/Prog/Lido/lido-oracle/app/oracle.py", line 310, in <module>
    w3.eth.call(tx)
  File "/Users/kirill/Prog/Lido/lido-oracle/venv/lib/python3.8/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/Users/kirill/Prog/Lido/lido-oracle/venv/lib/python3.8/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/Users/kirill/Prog/Lido/lido-oracle/venv/lib/python3.8/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/Users/kirill/Prog/Lido/lido-oracle/venv/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 521, in raise_solidity_error_on_revert
    raise SolidityError(response['error']['message'])
web3.exceptions.SolidityError: execution reverted: ALREADY_SUBMITTED
```
